configure_dotfiles: no
configure_sudoers: no
configure_terminal: no
configure_osx: no

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - dteoh/sqa

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - git
  - go
  - elixir
  - httpie
  - sqlite
  - node
  - nvm
  - cowsay
  - pipenv
  - openssl
  - pv
  - wget
  - tldr
  - bat

homebrew_cask_apps:
  - chromedriver
  - docker
  - dropbox
  - google-chrome
  - brave-browser
  - jetbrains-toolbox
  - onedrive
  - alfred
  - postman
  - iterm2
  - karabiner-elements
  - keybase
  - microsoft-word
  - microsoft-excel
  - microsoft-powerpoint
  - private-internet-access
  - skype
  - spotify
  - visual-studio-code
  - dozer
  - rectangle
  - slowquitapps
  - macs-fan-control

mas_installed_apps:
- { id: 497799835, name: "Xcode" }
- { id: 732710998, name: "Enpass - Password Manager" }
- { id: 1474276998, name: "HP Smart" }
- { id: 747648890, name: "Telegram" }
- { id: 1147396723, name: "WhatsApp Desktop" }
- { id: 937984704, name: "Amphetamine" }
- { id: 823766827, name: "OneDrive" }

mas_email: ""
mas_password: ""