configure_dotfiles: yes
configure_sudoers: no
configure_terminal: no
configure_osx: no

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - dteoh/sqa
  - homebrew/cask-fonts

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - git
  - elixir
  - httpie
  - node
  - nvm
  - pipenv
  - openssl
  - pv
  - wget
  - tldr
  - bat
  - htop
  - up
  - fasd

homebrew_cask_apps:
  - chromedriver
  - docker
  - dropbox
  - google-chrome
  - brave-browser
  - jetbrains-toolbox
  - onedrive
  - alfred
  - postman
  - iterm2
  - karabiner-elements
  - private-internet-access
  - spotify
  - visual-studio-code
  - dozer
  - rectangle
  - macs-fan-control
  - pock
  - font-victor-mono
  - font-meslo-lg-nerd-font
  - alt-tab

mas_installed_apps:
- { id: 497799835, name: "Xcode" }
- { id: 732710998, name: "Enpass - Password Manager" }
- { id: 1474276998, name: "HP Smart" }
- { id: 747648890, name: "Telegram" }
- { id: 1147396723, name: "WhatsApp Desktop" }
- { id: 937984704, name: "Amphetamine" }
- { id: 823766827, name: "OneDrive" }

mas_email: ""
mas_password: ""